//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public Aluno()
        {
            this.AlunoExercicioLicoes = new HashSet<AlunoExercicioLicao>();
            this.AlunoLicoes = new HashSet<AlunoLicao>();
            this.AlunoTesteExercicios = new HashSet<AlunoTesteExercicio>();
            this.Aprendizagens = new HashSet<Aprendizagem>();
        }
    
        public int IdAluno { get; set; }
        public string Nome { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public byte Dica { get; set; }
        public int Tema { get; set; }
        public byte Explicacao { get; set; }
        public int Pontuacao { get; set; }
    
        public virtual ICollection<AlunoExercicioLicao> AlunoExercicioLicoes { get; set; }
        public virtual ICollection<AlunoLicao> AlunoLicoes { get; set; }
        public virtual ICollection<AlunoTesteExercicio> AlunoTesteExercicios { get; set; }
        public virtual ICollection<Aprendizagem> Aprendizagens { get; set; }
    }
}
