//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprendizagem
    {
        public int IdAprendizagem { get; set; }
        public int Aluno { get; set; }
        public System.DateTime Data { get; set; }
        public double Estado { get; set; }
        public int Tipo { get; set; }
    
        public virtual Aluno Aluno1 { get; set; }
    }
}
