//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dica
    {
        public int IdDica { get; set; }
        public int Exercicio { get; set; }
        public string Texto { get; set; }
        public byte[] Imagem { get; set; }
    
        public virtual Exercicio ExercicioAQuePertence { get; set; }
    }
}
