//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicio
    {
        public Exercicio()
        {
            this.AlunoExercicioLicoes = new HashSet<AlunoExercicioLicao>();
            this.AlunoTesteExercicios = new HashSet<AlunoTesteExercicio>();
            this.Dicas = new HashSet<Dica>();
            this.Respostas = new HashSet<Resposta>();
            this.LicoesEmQueEsta = new HashSet<Licao>();
            this.TestesEmQueEsta = new HashSet<Teste>();
        }
    
        public int IdExercicio { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Administrador { get; set; }
        public string Texto { get; set; }
        public int Dificuldade { get; set; }
        public byte[] Imagem { get; set; }
        public int TempoEx { get; set; }
    
        public virtual Administrador AdministradorCriou { get; set; }
        public virtual ICollection<AlunoExercicioLicao> AlunoExercicioLicoes { get; set; }
        public virtual ICollection<AlunoTesteExercicio> AlunoTesteExercicios { get; set; }
        public virtual ICollection<Dica> Dicas { get; set; }
        public virtual Tipo TipoExercicio { get; set; }
        public virtual ICollection<Resposta> Respostas { get; set; }
        public virtual ICollection<Licao> LicoesEmQueEsta { get; set; }
        public virtual ICollection<Teste> TestesEmQueEsta { get; set; }
    }
}
