//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licao
    {
        public Licao()
        {
            this.AlunoExercicioLicoes = new HashSet<AlunoExercicioLicao>();
            this.AlunoLicoes = new HashSet<AlunoLicao>();
            this.Exercicios = new HashSet<Exercicio>();
        }
    
        public int idLicao { get; set; }
        public int NumExpl { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Administrador { get; set; }
        public string Texto { get; set; }
        public string Video { get; set; }
        public byte[] Imagem { get; set; }
        public int TempoLicao { get; set; }
    
        public virtual Administrador Administrador1 { get; set; }
        public virtual ICollection<AlunoExercicioLicao> AlunoExercicioLicoes { get; set; }
        public virtual ICollection<AlunoLicao> AlunoLicoes { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual ICollection<Exercicio> Exercicios { get; set; }
    }
}
