//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teste
    {
        public Teste()
        {
            this.AlunoTesteExercicios = new HashSet<AlunoTesteExercicio>();
            this.ExerciciosDoTeste = new HashSet<Exercicio>();
        }
    
        public int IdTeste { get; set; }
        public double Dificuldade { get; set; }
    
        public virtual ICollection<AlunoTesteExercicio> AlunoTesteExercicios { get; set; }
        public virtual ICollection<Exercicio> ExerciciosDoTeste { get; set; }
    }
}
