//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritMat.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Exercicios = new HashSet<Exercicio>();
            this.Licoes = new HashSet<Licao>();
        }
    
        public int IdTipo { get; set; }
        public string Area { get; set; }
    
        public virtual ICollection<Exercicio> Exercicios { get; set; }
        public virtual ICollection<Licao> Licoes { get; set; }
    }
}
